name: Update Data from Generator

on:
  schedule:
    - cron: '30 3 * * *' # KST 12시 30분
    - cron: '30 9 * * *' # KST 18시 30분
    - cron: '30 15 * * *' # KST 00시 30분
    - cron: '30 21 * * *' # KST 6시 30분
  workflow_dispatch: # Trigger for manual execution

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch RSS data
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          git clone https://$PAT@github.com/tsryu/data-generator.git
          cp data-generator/data/{rssData.json,apiData.json,webContent.json,buildTime.json} src/data/

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m 'Update data from generator'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build React app
        env:
          REACT_APP_GOOGLE_ADSENSE_CLIENT_ID: ${{ secrets.REACT_APP_GOOGLE_ADSENSE_CLIENT_ID }}
        run: |
          npm install -g yarn
          yarn
          yarn build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.2.0
        with:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build
